.TH QLOG 1 "2026-03-13" "QLog" "User Commands"
.SH NAME
qlog \- Amateur Radio logging application
.SH SYNOPSIS
.B qlog
.RI [ OPTIONS ]
.SH DESCRIPTION
QLog is a multiplatform Amateur Radio logging application.
It is based on the Qt framework and uses SQLite as database backend.
.PP
QLog aims to be as simple as possible, but to provide everything
the operator expects from the log.
.SH OPTIONS
.TP
.BR \-d ", " \-\-debug
Write debug messages to
.I ~/.local/share/hamradio/QLog/qlog_debug_YYYYMMDDhhmmss.log
.TP
.BR \-f ", " \-\-force\-update
Force update of all value lists (DXCC, SATs, etc.).
.TP
.BR \-l ", " \-\-language " " \fIcode\fR
Set language (e.g.\& \fBen\fR or \fBen_US\fR). Ignores environment setting.
.TP
.BR \-t ", " \-\-translation " " \fIpath\fR
Load a translation file (absolute or relative path to a QM file).
.TP
.BR \-h ", " \-\-help
Display help message and exit.
.TP
.BR \-v ", " \-\-version
Display version information and exit.
.SH FILES
.TP
.I ~/.config/hamradio/QLog.conf
Machine-specific settings.
.TP
.I ~/.local/share/hamradio/QLog/
Data directory.
.SH BUGS
Report bugs at <https://github.com/foldynl/QLog/issues>.
.SH SEE ALSO
.UR https://github.com/foldynl/QLog/wiki
QLog Wiki
.UE
.SH AUTHOR
Ladislav Foldyna (OK1MLG) <ok1mlg@gmail.com>
